### ISSUE TITLE
[question] Any clue why pug-as-jsx-loader doesn't work?

### ISSUE THREAD

**Issue by douggr** [preactjs-templates/default#23]
Regarding this https://github.com/bluewings/pug-as-jsx-loader/issues/29#issue-400954960.

The app was created using `preact-cli`:

```shell
$ preact create default preact-default --yarn
$ cd preact-default
$ yarn 
$ yarn add pug-as-jsx-loader
// create file.pug and import in any route
$ yarn dev
```

preact.config.js
```js
export default (config, env, helpers) => {
  config.module.loaders.push({
    test: /\.pug$/,
    use: ['babel-loader', 'pug-as-jsx-loader?transpiledFile=true'],
  });

  return config;
};
```

**Comment by bluewings** [comment]
@douggr 
I have added an example for `preact-template/default` below.
https://github.com/bluewings/pug-as-jsx-loader/tree/master/examples/preact-default

In `preact.config.js`, you need to set babel preset for the `.pug` file.
and `npm install babel-preset-react --save-dev`
https://github.com/bluewings/pug-as-jsx-loader/blob/b74ad079b8fd8c80d1ad487203c14834b1591a77/examples/preact-default/preact.config.js#L12-L26

If you are using Babel 7 or higher, try the options below
```js
  loader: require.resolve('babel-loader'),
  options: {
    presets: ['@babel/preset-env', '@babel/preset-react'],
  },
```

Enjoy using the following Pug template!, Thank you!
https://github.com/bluewings/pug-as-jsx-loader/tree/b74ad079b8fd8c80d1ad487203c14834b1591a77/examples/preact-default/src/routes/home

**Comment by douggr** [comment]
Awesome! Many thanks!
