### ISSUE TITLE
How to add React to Preact aliasing via `preact/compat`?

### ISSUE THREAD

**Issue by fooness** [preactjs-templates/default#46]
Hello everyone. I just created my first preact application via `preact-cli` with the `default` template, hence posting this question here in the correspoding repository.

The Getting Started guide states [Aliasing React to Preact](https://preactjs.com/guide/v10/getting-started/#aliasing-react-to-preact), but unfortunately I don’t quite know how we’d do that. There’s no webpack or parcel config in the created application blueprint, or am I missing something?

Could someone please explain, how to add `preact/compat` to our application?

**Comment by rschristian** [comment]
Hello, 

This is done for you already if you're using `preact-cli`. Under the hood it uses Webpack, and you can customize configs by using a `preact.config.js` file.

Let me know if you have any more questions.

**Comment by rschristian** [comment]
Note the "Aliasing React to Preact" section is under "Integrating Into an Existing pipeline". Above "Integrating..." there's "Best Practices Empowered by Preact CLI". That's what you want to read if you're using Preact CLI.

**Comment by fooness** [comment]
> […] and you can customize configs by using a `preact.config.js` file.

I tried searching for that file via `find`. If it, indeed, does not exist in my project … could you please tell me where to create it, and is there some official example of that file which I, unfortunately, also did not find in the preactjs repositories?

> Above "Integrating..." there's "Best Practices Empowered by Preact CLI". That's what you want to read if you're using Preact CLI.

<del>I will check that out. Thank you very much for your answers!</del> Oh, yeah, I definitely read that part. It also explicitly states that `preact-cli` does not need any configuration to get started … so maybe, indeed, I would have to create that `preact.config.js` myself then.

> Let me know if you have any more questions.

Slightly offtopic, but I wonder what the `src/sw.js` file of the default template is for … and if it could be deleted.

**Comment by rschristian** [comment]
`preact.config.js` and the service worker (`sw.js`) have documentation in the CLI repo: https://github.com/preactjs/preact-cli

But yes. The config file is a way for you to hop in and override some value or add some functionality. If you don't use one that means you're happy with the defaults. An example of one can be found in the Typescript template: https://github.com/preactjs-templates/typescript/blob/master/template/preact.config.js
